### ISSUE TITLE
Print Function to allow for PDF Printing of single pages

### ISSUE THREAD

**Issue by hbuchner** [jwiesel/sfdcCommander#1]
It is currently not possible to print the current page reasonable. A print formatting to support PDF storage in Chrome or PDFCreator printing in IE would be helpfull.

**Comment by jwiesel** [comment]
Todo: Add separate stylesheet for printer
- Hide Buttons: Print & Back
- Hide Quick-Navigation
- Change appearance of content header: formatting of headline 2
